// Generated by Haxe TypeScript Declaration Generator :)

export class SomeTsClass {
	constructor(someArg: string);
}

export namespace server {
	class SuperServerComponent {
		constructor();
		saySomething(phrase: string): void;
	}
}

export namespace server {
	class TinkAPI {
		private constructor();
	}
}