// Generated by Haxe 4.0.0-rc.2+92c7833
(function ($global) { "use strict";
var Std = function() { };
Std.parseInt = function(x) {
	var v = parseInt(x, x && x[0]=="0" && (x[1]=="x" || x[1]=="X") ? 16 : 10);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var js_npm_Express = require("express");
var js_npm_express_Router = require("express").Router;
var js_npm_express_Static = require("express").static;
var server_Config = function() { };
var server_Main = function() { };
server_Main.main = function() {
	server_Main.app.set("view engine","ejs");
	server_Main.app.use("/assets",new js_npm_express_Static(path.join(__dirname,"..","..","..","assets")));
	server_Main.app.use(server_Routes.apiRouter());
	server_Main.app.use(function(req,res) {
	});
	server_Main.app.listen(server_Config.SERVER_PORT);
};
var server_Routes = function() { };
server_Routes.apiRouter = function() {
	var bodyParser = require("body-parser");
	var db = require("db");
	var router = js_npm_express_Router();
	router.use(bodyParser.json());
	router.get("/api/users",function(req,res) {
		res.json(db.users);
		return;
	});
	router.get("/api/user/:userId",function(req1,res1) {
		var userId = req1.params.userId;
		var tmp = db.getUserById(userId);
		res1.json(tmp);
		return;
	});
	router.post("/api/set-user",function(req2,res2) {
		res2.send("ok");
	});
	return router;
};
server_Config.SERVER_PORT = Std.parseInt(process.env["PORT"] != null ? process.env["PORT"] : "3000");
server_Main.app = new js_npm_Express();
server_Main.main();
})({});
